
project_id = "asexlqsjachwhabzvzwk"

[functions.generate-invitation]
verify_jwt = true

[functions.scrape-venues]
verify_jwt = true

[functions.custom-email]
verify_jwt = false

[functions.generate-checklist]
verify_jwt = true

[functions.event-ai-assistant]
verify_jwt = false

[functions.generate-event]
verify_jwt = false
