
project_id = "asexlqsjachwhabzvzwk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.custom-email]
verify_jwt = false
[functions.marketplace-api]
verify_jwt = false
[functions.venue-availability]
verify_jwt = false
