
project_id = "asexlqsjachwhabzvzwk"

[functions.generate-invitation]
verify_jwt = true

[functions.scrape-venues]
verify_jwt = true

[functions.custom-email]
verify_jwt = false

[functions.checklist]
verify_jwt = true

[functions.event-ai-assistant]
verify_jwt = false

[functions.generate-event]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false

[functions.welcome-email]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true
